apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: candidate
  name: candidate
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: candidate
    spec:
      containers:
        - image: garystafford/candidate-service:kub-aks-0.5.121
          name: candidate
          ports:
          - containerPort: 8080
          resources: {}
          env:
            - name: AZURE_SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-service-bus
                  key: connection-string
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: azure-cosmosdb-candidate
                  key: connection-string
          command: ["/bin/sh"]
          args: ["-c", "java -Dspring.profiles.active=kub-aks -Dlogging.level.root=DEBUG -Djava.security.egd=file:/dev/./urandom -jar /candidate/candidate-service.jar"]
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
