apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - image: garystafford/voter-client:kub-aks-0.5.58
        name: client
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
