apiVersion: extensions/v1beta1
kind: Service
metadata:
  labels:
    io.kompose.service: election
  name: election
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: election
status:
  loadBalancer: {}
