apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voter-api
  labels:
    io.kompose.service: election
  name: election
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: election
    spec:
      containers:
      - image: garystafford/election-service:kub-aks-0.5.44
        name: election
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: AZURE_SERVICE_BUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-service-bus
                key: connection-string
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: azure-cosmosdb-election
                key: connection-string
        command: ["/bin/sh"]
        args: ["-c", "java -Dspring.profiles.active=kub-aks -Dlogging.level.root=DEBUG -Djava.security.egd=file:/dev/./urandom -jar /election/election-service.jar"]
        imagePullPolicy: Always
      restartPolicy: Always
status: {}
